import type { Metadata } from "next";
import { Navbar } from "@app/components/navbar";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta charSet="utf-8" />
      <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      <meta name="viewport" content="width=device-width" />

      <title>DAO</title>
      </head>
      <body className="flex flex-col bg-white-as-heaven min-h-[100vh] font-inter text-black">
        <Navbar/>
        {children}</body>
      
    </html>
  );
}

